# Site settings
description: N.B. This is a web app created for a university course, not an operational site.
permalink: pretty
github: ethan-nelson/radarlabissuer
baseurl: #

# Build settings
markdown: kramdown

# Custom settings
imagedir: /images/

# Map settings
mapdir: /images/maptiles/{z}/{x}/{y}.png
attribution: "Map Data: Copyright OpenStreetMap contributors (https://osm.org)"
mapcenter: "[32.79, -90.18]"
mapzoom: 7

# Radar image settings
radarimg: "/images/radar/latest.png"  # Note this must be the _full_ path following the FQDN (so if your site sits at /issue/, include that here)
radarbounds: "[[32.425, -100.85], [38.25, -93.75]]"

# Storm reports
reportsfile: "/reports.geoJSON"


starttime: "20:00"
endtime: "22:00"

houroffset: 6
minuteoffset: -30
